name: business_card_scanner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ^3.5.2

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  #User interface / UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.3.0
  gap: ^3.0.1
  flutter_expandable_fab: ^2.5.2
  scanning_effect: ^1.0.11

  #backend
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Dependency Injection
 # get_it: ^7.6.4
 # injectable: ^2.3.2
  
  # Routing
  go_router: ^15.1.0
  
  # Code Generation
 # freezed_annotation: ^2.4.1
 # json_annotation: ^4.8.1
  
  # Storage
 # isar: ^3.1.0+1
 # isar_flutter_libs: ^3.1.0+1

  
  # Share & Export
  share_plus: ^11.1.0
  url_launcher: ^6.2.1
  
  # QR Code
 # qr_flutter: ^4.1.0
 # mobile_scanner: ^3.5.6
  
  # Contacts
  flutter_contacts: ^1.1.7+1
  
  # Utilities /// Camera & OCR
  equatable: ^2.0.5
#  shared_preferences: ^2.2.2
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.12.0
  permission_handler: ^11.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  pdf: ^3.10.8
  file_picker: ^8.0.5
  path_provider: ^2.1.4
  path: ^1.9.0
  syncfusion_flutter_pdfviewer: ^27.1.48
  syncfusion_flutter_pdf: ^27.1.48
  
  # Network & API
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  
  # Testing
#  bloc_test: ^9.1.5
#  mocktail: ^1.0.1
#  golden_toolkit: ^0.15.0
  
  # Linting
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
